<?php
namespace ch\keepitnative\tests\formmailer\src\tests\src;

use ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection;

require_once __DIR__.'/../../../src/csrfprotection/CsrfProtection.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 14:50:19.
 */
class CsrfTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CsrfProtection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CsrfProtection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::setInput
     * @todo   Implement testSetInput().
     */
    public function testSetInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::getInput
     * @todo   Implement testGetInput().
     */
    public function testGetInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::setHash
     * @todo   Implement testSetHash().
     */
    public function testSetHash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::getHash
     * @todo   Implement testGetHash().
     */
    public function testGetHash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::setRandomtoken
     * @todo   Implement testSetRandomtoken().
     */
    public function testSetRandomtoken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::getRandomtoken
     * @todo   Implement testGetRandomtoken().
     */
    public function testGetRandomtoken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::setSession
     * @todo   Implement testSetSession().
     */
    public function testSetSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::getSession
     * @todo   Implement testGetSession().
     */
    public function testGetSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::createToken
     * @todo   Implement testCreateToken().
     */
    public function testCreateToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::createTokenField
     * @todo   Implement testCreateTokenField().
     */
    public function testCreateTokenField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\csrfprotection\CsrfProtection::isInValidToken
     * @todo   Implement testIsInValidToken().
     */
    public function testIsInValidToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
