<?php
namespace ch\keepitnative\tests\formmailer\src\tests\src;
use ch\keepitnative\formmailer\src\error\Error;
use ch\keepitnative\formmailer\src\validation\Validation;

require_once __DIR__.'/../../../src/validation/Validation.php';
require_once __DIR__.'/../../../src/error/Error.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 16:21:26.
 */
class ValidtionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Validation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $error = new Error();
        $this->object = new Validation($error);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ch\keepitnative\formmailer\src\validation\Validation::setErrors
     * @todo   Implement testSetErrors().
     */
    public function testSetErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\validation\Validation::getErrors
     * @todo   Implement testGetErrors().
     */
    public function testGetErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\validation\Validation::validate
     * @todo   Implement testValidate().
     */
    public function testValidate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\validation\Validation::email
     * @todo   Implement testEmail().
     */
    public function testEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\validation\Validation::text
     * @todo   Implement testText().
     */
    public function testText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\validation\Validation::numeric
     * @todo   Implement testNumeric().
     */
    public function testNumeric()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\validation\Validation::required
     * @todo   Implement testRequired().
     */
    public function testRequired()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
