<?php
namespace ch\keepitnative\tests\formmailer\src\tests\src;

use ch\keepitnative\formmailer\src\registry\Registry;

require_once __DIR__.'/../../../src/registry/Registry.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 16:43:45.
 */
class RegistryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Registry
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = Registry::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ch\keepitnative\formmailer\src\registry\Registry::setValues
     * @todo   Implement testSetValues().
     */
    public function testSetValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\registry\Registry::getValues
     * @todo   Implement testGetValues().
     */
    public function testGetValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\registry\Registry::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\registry\Registry::setRequest
     * @todo   Implement testSetRequest().
     */
    public function testSetRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\registry\Registry::setResponse
     * @todo   Implement testSetResponse().
     */
    public function testSetResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\registry\Registry::getRequest
     * @todo   Implement testGetRequest().
     */
    public function testGetRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\registry\Registry::getResponse
     * @todo   Implement testGetResponse().
     */
    public function testGetResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
