<?php
namespace ch\keepitnative\tests\formmailer\src\tests\src;
use ch\keepitnative\formmailer\src\error\Error;

require_once __DIR__.'/../../../src/error/Error.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 14:50:31.
 */
class ErrorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Error
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Error;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ch\keepitnative\formmailer\src\error\Error::getErrors
     * @todo   Implement testGetErrors().
     */
    public function testGetErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\error\Error::setErrors
     * @todo   Implement testSetErrors().
     */
    public function testSetErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\error\Error::getMsg
     * @todo   Implement testGetMsg().
     */
    public function testGetMsg()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\error\Error::setMsg
     * @todo   Implement testSetMsg().
     */
    public function testSetMsg()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
