<?php
namespace ch\keepitnative\tests\formmailer\src\tests\src;

use ch\keepitnative\formmailer\src\input\Input;
use ch\keepitnative\formmailer\src\request\HttpRequest;
use ch\keepitnative\formmailer\src\response\HttpResponse;
use ch\keepitnative\formmailer\src\session\Session;

require_once __DIR__.'/../../../src/session/Session.php';
require_once __DIR__.'/../../../src/input/Input.php';
require_once __DIR__ . '/../../../src/--response/HttpResponse.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 16:39:17.
 */
class SessionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Session
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $input = new Input();
        $response = new HttpResponse();
        $this->object = new Session($input,$response);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ch\keepitnative\formmailer\src\session\Session::isSessionStarted
     * @todo   Implement testIsSessionStarted().
     */
    public function testIsSessionStarted()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\session\Session::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\session\Session::__clone
     * @todo   Implement test__clone().
     */
    public function test__clone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\session\Session::setUserdata
     * @todo   Implement testSetUserdata().
     */
    public function testSetUserdata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\session\Session::getUserdata
     * @todo   Implement testGetUserdata().
     */
    public function testGetUserdata()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\session\Session::regen
     * @todo   Implement testRegen().
     */
    public function testRegen()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\session\Session::setUserdatas
     * @todo   Implement testSetUserdatas().
     */
    public function testSetUserdatas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\session\Session::issetParameter
     * @todo   Implement testIssetParameter().
     */
    public function testIssetParameter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\session\Session::unsetAll
     * @todo   Implement testUnsetAll().
     */
    public function testUnsetAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
