<?php
namespace ch\keepitnative\tests\formmailer\src\tests\src;

use ch\keepitnative\formmailer\src\captcha\Captcha;
use ch\keepitnative\formmailer\src\error\Error;
use ch\keepitnative\formmailer\src\input\Input;
use ch\keepitnative\formmailer\src\response\HttpResponse;
use ch\keepitnative\formmailer\src\session\Session;

require_once __DIR__.'/../../../src/captcha/Captcha.php';
require_once __DIR__.'/../../../src/error/Error.php';
require_once __DIR__.'/../../../src/session/Session.php';
require_once __DIR__.'/../../../src/input/Input.php';
require_once __DIR__ . '/../../../src/--response/HttpResponse.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 14:46:19.
 */
class CaptchaTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Captcha
     */
    protected $object;
    /**
     * @var string
     */
    protected $tmpPath = './tmp';

    /**
     * @var string
     */
    protected $fontsDir = './fonts';

    /**
     * @var string
     */
    protected $bgPath = './img/bg.png';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->fontsDir = './fonts';

        //serverseitige validierungs regeln
        $rules = array(
            'email' => 'email|required',
            'nachname' => 'required|text',
            'vorname' => 'required|text',
            'strassenr' => 'required|text',
            'plzort' => 'required|text',
            'telefon' => 'required|text',
            'art' => 'required|text',
            'groesse' => 'required|text'
        );

        $options = [
            'thema' => 'Offerte',
            'baseUrl' => "http://dev.02.php-upload-formmailer.me/",
            'emailRecipientFirma' => "whatever@whoelse.com",
            'data' => $_FILES,
            'uploadDir' => "./uploads/",
            'maxSize' => 2000000, //=2MB
            'formats' => "gif,png,jpg,pdf,eps,ai",
            'rules' => $rules,
            'captchaBenutzen' => true,
            'fontsDir' => './fonts',
            'tmpDir' => './tmp',
            'bgPath' => __DIR__.'/../../../img/bg.png',

        ];
        $input = new Input();
        $response = new HttpResponse();
        $session = new Session($input,$response);
        $error = new Error();
        $this->object =  Captcha::getInstance($options,$session,$error);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::getSession
     * @todo   Implement testGetSession().
     */
    public function testGetSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::setSession
     * @todo   Implement testSetSession().
     */
    public function testSetSession()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::setBgPath
     * @todo   Implement testSetBgPath().
     */
    public function testSetBgPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::getBgPath
     * @todo   Implement testGetBgPath().
     */
    public function testGetBgPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::setFontsDir
     * @todo   Implement testSetFontsDir().
     */
    public function testSetFontsDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::getFontsDir
     * @todo   Implement testGetFontsDir().
     */
    public function testGetFontsDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::setTxtCode
     * @todo   Implement testSetTxtCode().
     */
    public function testSetTxtCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::getTxtCode
     * @todo   Implement testGetTxtCode().
     */
    public function testGetTxtCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::setFileName
     * @todo   Implement testSetFileName().
     */
    public function testSetFileName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::getFileName
     * @todo   Implement testGetFileName().
     */
    public function testGetFileName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::setTmpPath
     * @todo   Implement testSetTmpPath().
     */
    public function testSetTmpPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::getTmpPath
     * @todo   Implement testGetTmpPath().
     */
    public function testGetTmpPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::setSessionCode
     * @todo   Implement testSetSessionCode().
     */
    public function testSetSessionCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::getSessionCode
     * @todo   Implement testGetSessionCode().
     */
    public function testGetSessionCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::setSessionFileName
     * @todo   Implement testSetSessionFileName().
     */
    public function testSetSessionFileName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::resetSessionFileName
     * @todo   Implement testResetSessionFileName().
     */
    public function testResetSessionFileName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::getSessionFileName
     * @todo   Implement testGetSessionFileName().
     */
    public function testGetSessionFileName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::destroyImage
     * @todo   Implement testDestroyImage().
     */
    public function testDestroyImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::getError
     * @todo   Implement testGetError().
     */
    public function testGetError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::setError
     * @todo   Implement testSetError().
     */
    public function testSetError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::checkCaptcha
     * @todo   Implement testCheckCaptcha().
     */
    public function testCheckCaptcha()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::sessionStart
     * @todo   Implement testSessionStart().
     */
    public function testSessionStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::createCaptcha
     * @todo   Implement testCreateCaptcha().
     */
    public function testCreateCaptcha()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::createText
     * @todo   Implement testCreateText().
     */
    public function testCreateText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::createUniqueImageName
     * @todo   Implement testCreateUniqueImageName().
     */
    public function testCreateUniqueImageName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\captcha\Captcha::outputImage
     * @todo   Implement testOutputImage().
     */
    public function testOutputImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
