<?php
namespace ch\keepitnative\tests\formmailer\src\tests\src;

use ch\keepitnative\formmailer\src\error\Error;
use ch\keepitnative\formmailer\src\input\Input;
use ch\keepitnative\formmailer\src\mailer\Mailer;

require_once __DIR__.'/../../../src/mailer/Mailer.php';
require_once __DIR__.'/../../../src/error/Error.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 15:24:56.
 */
class MailerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Mailer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $input = new Input();
        $error = new Error();
        $this->object = new Mailer($input,$error);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ch\keepitnative\formmailer\src\mailer\Mailer::setHash
     * @todo   Implement testSetHash().
     */
    public function testSetHash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\mailer\Mailer::getHash
     * @todo   Implement testGetHash().
     */
    public function testGetHash()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\mailer\Mailer::setErrors
     * @todo   Implement testSetErrors().
     */
    public function testSetErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\mailer\Mailer::getErrors
     * @todo   Implement testGetErrors().
     */
    public function testGetErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\mailer\Mailer::setInput
     * @todo   Implement testSetInput().
     */
    public function testSetInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\mailer\Mailer::getInput
     * @todo   Implement testGetInput().
     */
    public function testGetInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\mailer\Mailer::getMsg
     * @todo   Implement testGetMsg().
     */
    public function testGetMsg()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\mailer\Mailer::sendMail
     * @todo   Implement testSendMail().
     */
    public function testSendMail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
