<?php
namespace ch\keepitnative\tests\formmailer\src\tests\src;
require_once __DIR__.'/../../../src/psr4autoloader/Psr4AutoloaderClass.php';
use ch\keepitnative\formmailer\src\psr4autoloader\Psr4AutoloaderClass;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-12 at 16:52:24.
 */
class Psr4AutoloaderClassTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Psr4AutoloaderClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Psr4AutoloaderClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ch\keepitnative\formmailer\src\psr4autoloader\Psr4AutoloaderClass::register
     * @todo   Implement testRegister().
     */
    public function testRegister()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\psr4autoloader\Psr4AutoloaderClass::addNamespace
     * @todo   Implement testAddNamespace().
     */
    public function testAddNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ch\keepitnative\formmailer\src\psr4autoloader\Psr4AutoloaderClass::loadClass
     * @todo   Implement testLoadClass().
     */
    public function testLoadClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
